maintainer       'Heavy Water Operations, LLC'
maintainer_email 'ops@hw-ops.com'
license          'Apache-2.0'
description      'Installs/Configures omnibus-ninefold-ruby'
version          '0.1.0'

name 'omnibus-ninefold'
depends 'ruby_installer'
depends 'git'
depends 'ubuntu'
